sbcgua/ajson

src/zcl_ajson.clas.abap, src/zcl_ajson.clas.testclasses.abap, src/zif_ajson_reader.intf.abap
=> rename value to get

src/zcl_ajson.clas.abap, src/zcl_ajson.clas.locals_imp.abap, src/zcl_ajson.clas.testclasses.abap, src/zif_ajson_reader.intf.abap
=> Date parsing

README.md
Tested on 702 SP 21 and the unit tests work perfectly :-)
=> Support for 7.02 or higher

README.md
=> Fix quotes

README.md, src/zcl_ajson.clas.abap, src/zcl_ajson.clas.testclasses.abap, src/zif_ajson_reader.intf.abap
=> Get node type

src/zcl_ajson.clas.abap, src/zcl_ajson.clas.locals_imp.abap, src/zcl_ajson.clas.testclasses.abap, src/zif_ajson_writer.intf.abap
=> Add set_with_type to writer

abaplint.json, src/zcl_ajson.clas.abap, src/zcl_ajson.clas.locals_imp.abap, src/zcl_ajson.clas.testclasses.abap
@larshp would it be ok for your purposes ?
=> prefix local variables

README.md, src/zcl_ajson.clas.abap, src/zcl_ajson.clas.testclasses.abap, src/zif_ajson_writer.intf.abap
Postprocessing of #27
@mbtools are you ok this ?
=> Merge set and set with type

README.md, src/zcl_ajson_utilities.clas.abap, src/zcl_ajson_utilities.clas.testclasses.abap, src/zcl_ajson_utilities.clas.xml
=> Add diff utility

abaplint.json, src/zcl_ajson.clas.abap, src/zcl_ajson.clas.locals_imp.abap, src/zcl_ajson.clas.testclasses.abap, src/zcl_ajson_mapping.clas.locals_imp.abap
=> enable rule unused_variables

README.md
=> Documentation custom mapping

src/zcl_ajson.clas.testclasses.abap
=> more basic unit tests

src/zcl_ajson.clas.locals_imp.abap, src/zcl_ajson.clas.testclasses.abap
Support conversion between json timestamp (2020-07-28T00:00:00Z) to abap (20200728000000)
=> Timestamps to_abap

src/zcl_ajson.clas.locals_imp.abap, src/zcl_ajson.clas.testclasses.abap
=> Fix ITAB_DUPLICATE_KEY when using hashed table

src/zcl_ajson.clas.abap, src/zcl_ajson.clas.locals_imp.abap
use inline constants instead of referring to data element TZNZONE
=> Avoid use of TZNZONE

src/zcl_ajson.clas.testclasses.abap
splits set_value unit test to one method per testcase
=> unit test: split set_value into method per case

src/zcl_ajson.clas.testclasses.abap
=> replace use of xfeld with xsdboolean

abaplint.json, src/zajson_perf_test.prog.abap, src/zajson_perf_test.prog.xml
@larshp is there a way to exclude certain object when merging into abapGit ? Any unexpected harm from such a PR ?
=> simple perf test

src/zcl_ajson.clas.locals_imp.abap
reduce max line length, https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#stick-to-a-reasonable-line-length
https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#put-comments-before-the-statement-they-relate-to
=> move comment

src/zcl_ajson_utilities.clas.abap
Consolidate 3 checks into 1 method
=> Refactor input check for utilities

src/zcl_ajson_utilities.clas.abap, src/zcl_ajson_utilities.clas.testclasses.abap
After #93
New method to merge two JSON objects
=> Add merge utility

src/zcl_ajson.clas.testclasses.abap
split unit test into one test per method
=> split unit test method set_bool

src/zcl_ajson.clas.locals_imp.abap
Consolidates used `type_kind` values into local interface
Closes #106
=> Replace literals with constants

src/zcl_ajson.clas.locals_imp.abap, src/zcl_ajson_mapping.clas.testclasses.abap
Changes to fix #110 
I added a new with the issue case
Unit tests runs ok
=> Restrict the apply of mapping conversions

src/zajson_perf_test.prog.abap, src/zcl_ajson.clas.abap, src/zcl_ajson.clas.locals_imp.abap, src/zcl_ajson.clas.testclasses.abap
=> Rewrite node, keep order

README.md, changelog.txt, src/zcl_ajson_filter_lib.clas.abap, src/zcl_ajson_filter_lib.clas.locals_imp.abap, src/zcl_ajson_filter_lib.clas.testclasses.abap
see docs
```abap
zcl_ajson_filter_lib=>create_path_filter( 
iv_skip_paths = '*/@*'
iv_pattern_search = abap_true ).
```
=> Pattern path filter

src/zcl_ajson.clas.locals_imp.abap
=> Fix warning related to timestamp rounding

src/zcl_ajson.clas.locals_imp.abap, src/zcl_ajson.clas.testclasses.abap
Add the possibility of converting by only corresponding fields from any to abap and creating UT for it.
=> #8 add convert by corresponding fields any to abap with unit tests

src/zcl_ajson.clas.testclasses.abap
=> Fix syntax error in ZCL_AJSON in 7.02

abaplint.json, src/zcl_ajson.clas.locals_imp.abap
- Enable `sy_modification` rule
=> Remove cases of modifying `syst` fields

src/zcl_ajson.clas.abap, src/zcl_ajson.clas.locals_imp.abap
=> refactoring: use ty_opts internally

src/zcl_ajson.clas.locals_imp.abap, src/zcl_ajson.clas.testclasses.abap
fixes #147
@mbtools have a look
=> More compatible xstr convertion

src/core/zcl_ajson.clas.abap, src/core/zcl_ajson.clas.testclasses.abap, src/core/zif_ajson.intf.abap
=> to_abap, expose corresponding

README.md, abaplint.jsonc, changelog.txt, src/core/zcl_ajson.clas.abap, src/core/zcl_ajson.clas.testclasses.abap, src/core/zif_ajson.intf.abap
closes #161
@christianguenter2 FYI
=> to_abap_corresponding_only instance flag

src/libs/zcl_ajson_utilities.clas.testclasses.abap
`assert_true` and `assert_false` do not exist in 702. Use `assert_equals` instead
=> Downport utilities testclass

src/core/zcl_ajson.clas.locals_imp.abap, src/core/zcl_ajson.clas.testclasses.abap
never used regex before, but tried to make it as similar as possible to the already existing date logic.
=> json_to_abap - added logic for type time

changelog.txt, src/core/zcl_ajson.clas.locals_imp.abap, src/core/zcl_ajson.clas.testclasses.abap
closes #179
stricter detection of timestamps
=> String as number

src/core/zcl_ajson.clas.testclasses.abap, transpile_for_testing.json
=> separate unicode UT

src/core/zcl_ajson.clas.abap, src/core/zcl_ajson.clas.locals_imp.abap, src/core/zcl_ajson.clas.testclasses.abap, src/core/zif_ajson.intf.abap, transpile_for_testing.json
Ref #200 
Completes the set methods.
=> Add `set_timestampl`

src/core/zcl_ajson.clas.abap, src/core/zcl_ajson.clas.testclasses.abap, src/core/zif_ajson.intf.abap
Counter part to `set_timestampl` (ref #202)
=> Add `get_timestampl`

src/core/zcl_ajson.clas.testclasses.abap
cc
https://abapgit.slack.com/archives/C4K5GM9D0/p1758512822386319
=> add unit tests for empty string/object

docsite/docs/40-reading.md
- Add details on json to abap type mapping
- Add explanation and example for ref to data
Ref #203
=> docs: ref to data
