- src/zcl_ajson.clas.abap
- src/zcl_ajson.clas.testclasses.abap
When inserting a structure inside an array, the index for 'object' should be zero. See test case 
Without the fix you get
```
/issues/1/       |end      |object |                        |1|2
/issues/2/       |end      |object |                        |2|2
```
But it should be
```
/issues/1/       |end      |object |                        |0|2
/issues/2/       |end      |object |                        |0|2
```
> Fix index when inserting a structure into an array

- .github/workflows/abaplint.yml
this should make it run a bit faster, plus avoid the warning,
> CI, use setup-node@v2

- README.md
- changelog.txt
- src/zcl_ajson.clas.abap
- src/zcl_ajson.clas.locals_imp.abap
- src/zcl_ajson.clas.testclasses.abap
- src/zif_ajson.intf.abap
to #38 
use `keep_item_order` to save struc field order and the serialize will pick it up.
@larshp ready for test, though I will add some docs and maybe refactor some stuff. But the feature is ready and covered with UTs.
P.S. I hope 2 extra table keys are ok for older system. 731 seems to support it ...
> item_order feature

- src/zcl_ajson.clas.abap
The double definition of the reader and writer interfaces is not necessary. It's already included in `zif_ajson`. On 702 it actually causes a dump when importing with abapGit. I suggest removing them from the class definition.
> Remove nested interfaces

- src/zcl_ajson.clas.locals_imp.abap
add data elements `abap_boolean`, `xsdboolean`, `flag` to be considered as json booleans
these 3 data elements are in the list of released objects for [Steampunk](https://blogs.sap.com/2019/08/20/its-steampunk-now/)
as a second step, I'd like to replace the use of XFELD in the unit tests to one of these 3 types => #75
> additional boolean types

- src/zcl_ajson.clas.locals_imp.abap
- src/zcl_ajson.clas.testclasses.abap
Replace "@PARSER" with "Line x, Offset y" in the parsing error message.
Example in abaplint editor:
> Add location to parsing error message

- src/zcl_ajson.clas.locals_imp.abap
the `_parse` method throws dynamic exception `cx_sxml_error`, this change catches these, if they occur somehow
> avoid possible spill of sxml exception

- src/zcl_ajson_utilities.clas.abap
- src/zcl_ajson_utilities.clas.testclasses.abap
Add option to keep empty arrays when determining diff.
Use case: Build diff to merge new abaplint options into existing abaplint.json (wip for https://github.com/abaplint/abaplint-sci-client)
> "Keep empty arrays" for diff utility

- src/zcl_ajson.clas.locals_imp.abap
- src/zcl_ajson_mapping.clas.testclasses.abap
Closes #95
Before
```json
{  
"code": "REPORT zfoobar.",
"fileName": "test.abap",
"profileInfo": {
}
}
```
After
```json
{  
"code": "REPORT zfoobar.",
"fileName": "test.abap",
"profileInfo": {
"showFullname": true,
"position": "bottom-center"
}
}
```
> Fix path when using CamelCase

- src/zcl_ajson.clas.locals_imp.abap
- src/zcl_ajson.clas.testclasses.abap
- src/zcl_ajson_mapping.clas.testclasses.abap
PR #96 was incomplete. It covered nested structures but not nested tables. 
- Test case `set_tab_nested_struct` fails with  `ITAB_DUPLICATE_KEY`
- Test case `to_json_nested_table` fails with incorrect JSON
Fix is to use `<root>-name` for the prefix for `convert_struc` and `convert_table` which is the correct value after mapping.
> Fix `ITAB_DUPLICATE_KEY` and CamelCase

- src/zcl_ajson.clas.locals_imp.abap
- src/zcl_ajson.clas.testclasses.abap
If the timestamp is initial, it should be converted into 0000-00-00T00:00:00Z, it is not the same that January 1, year 1
> Initial timestamp to 0000-00-00T00:00:00Z

- src/zcl_ajson.clas.locals_imp.abap
- src/zcl_ajson.clas.testclasses.abap
@mbtools FYI
- move to short is missing in 731 (probably in 701 too)
- and it does not accept strings in `convert`
So the former code didn't compile.
Will merge it just a bit later today.
> fix timestamp conversion in 731

- src/zcl_ajson.clas.testclasses.abap
https://abapedia.org/steampunk-2208-api/timezone.dtel.html
TZONREF is not released
https://github.com/abapGit/abapGit/pull/5764/checks?check_run_id=8421181012
> use data element TIMEZONE

- abaplint.json
- src/zcl_ajson.clas.locals_imp.abap
- src/zcl_ajson.clas.testclasses.abap
Enable `method_overwrites_builtin` rules
> Avoid overwriting built-in functions

- src/zcl_ajson.clas.locals_imp.abap
Using string instead of stack to handle path makes benchmark 3.4% faster.
You could get another 2-3% by removing the consistency check in closing a node:
Before:
```abap
when if_sxml_node=>co_nt_element_close.
data lo_close type ref to if_sxml_close_element.
lo_close ?= lo_node.
read table mt_stack index 1 into lr_stack_top.
delete mt_stack index 1.
if lo_close->qname-name <> lr_stack_top->type.
raise( 'Unexpected closing node type' ).
endif.
```
After:
```abap
when if_sxml_node=>co_nt_element_close.
delete mt_stack index 1.
```
> Performance: Speed-up parsing

- src/core/zcl_ajson.clas.abap
Testing this code:
```abap
DATA:
BEGIN OF ls_record,
records TYPE stringtab,
END OF ls_record.
TYPES:
ty_packed TYPE p LENGTH 16 DECIMALS 6.
DATA(index) = 0.
DO 5000 TIMES.
index = index + 1.
INSERT |Line{ index }| INTO TABLE ls_record-records.
ENDDO.
DATA(ajson) = zcl_ajson=>create_empty( ).
ajson->set( iv_path = `/` iv_val = ls_record ).
GET RUN TIME FIELD DATA(l_start).
DO 5000 TIMES.
ajson->slice( `records` ).
ENDDO.
GET RUN TIME FIELD DATA(l_end).
out->write( |{ l_start } -> { l_end }| ).
out->write( |Runtime: { CONV ty_packed( ( l_end - l_start ) / 1000000 ) NUMBER = USER } seconds| ).
```
Runtime before: 57,843338 seconds
Runtime after: 33,875135 seconds
Tests success
> Slice performance

- src/core/zcl_ajson.clas.testclasses.abap
add unit test with total 2 rows instead of 4
will make it easier for me to debug open-abap runtime bug
> add unit test: to_abap_array_of_arrays_simple

- src/core/zcl_ajson.clas.testclasses.abap
not sure why the chaining rule was disabled https://github.com/sbcgua/ajson/commit/01a170dda1d4acb5d340f1308f3c8b7dfa4bb13d ?
> downport to 702

- src/core/zcl_ajson.clas.abap
- src/core/zcl_ajson.clas.locals_imp.abap
- src/core/zcl_ajson.clas.testclasses.abap
When adding or changing nodes using set with keep item order on, the new node was always added with order = 0 (first position). This destroyed the original order. It also made it impossible to generate a JSON where the nodes should to be in a specific order, which is the expectation when setting "keep item order".
The fix preserves the order when changing nodes and also counts up the order when adding new nodes (so they keep in the order they where inserted).
Technical background: 
Keep item order is based on secondary index of the nodes table. However, if all order values are 0, then the sort order is not well defined and does not necessarily match the order in which nodes where inserted.
> Fix set with keep item order

- README.md
- changelog.txt
- src/core/zcl_ajson.clas.abap
- src/core/zcl_ajson.clas.locals_imp.abap
- src/core/zcl_ajson.clas.testclasses.abap
Option to keep node order in parsed json. FYI @larshp @mbtools 
ref: #165
> Keep item order when parsing

- src/core/zcl_ajson.clas.locals_imp.abap
- src/core/zcl_ajson.clas.testclasses.abap
In recursive calls of convert_struc() on suffixed include structures, the data holds the entire structure that the include structure is part of, so components of the include are suffixed, however the type is determined from the include structure alone, so the component list holds component names without their suffix. This leads to an ASSERTION_FAILURE error after component assignment fails because the names do not match.
> Fix: assertion failure caused by include structures with suffixes

- src/core/zcl_ajson.clas.abap
- src/core/zcl_ajson.clas.testclasses.abap
By default `touch_array` inserts the array at the top of the node. When keep order is set to true, `touch_array` will now insert *new* arrays at the end of the node. 
PS: Overwritting existing nodes already kept their position.
Closes #177
> Fix `touch_array` with keep order

- src/core/zcl_ajson.clas.locals_imp.abap
- src/core/zcl_ajson.clas.testclasses.abap
When filtering an array with >= 10 entries, the order is mixed up
> fixed array sort when filtering

- src/core/zcl_ajson.clas.locals_imp.abap
- src/core/zcl_ajson.clas.testclasses.abap
This PR reproduces the issue that is tracked https://github.com/sbcgua/ajson/issues/181 and contains a fix proposal.
> JSON_TO_ABAP: fix compressed JSON array to sorted/hashed table keeping components problem

- src/core/zcl_ajson.clas.abap
- src/core/zcl_ajson.clas.locals_imp.abap
- src/core/zcl_ajson.clas.testclasses.abap
Allows several types of input instead of just `string`.
Closes #189
PS: Cosmetic change for type constants
> Support `xstring` and `string_table` as input for parser

- abaplint.jsonc
- src/core/zcl_ajson.clas.locals_imp.abap
- src/core/zcl_ajson.clas.testclasses.abap
- src/perf/zajson_perf_test.prog.abap
I added tests for handling of special characters - like slashes, quotes, and unicode - in element names, paths, and values. Everything - except of one case - was working but now we know for sure 😃 
The special case is a slash in an element name that has sub-objects: `"contains/slash": "test"` is ok, but `"contains/slash": { "test": 1 }` is not. As suggested in #169, I replaced the slash with a `tab`. Parsing now works well 👍 
For methods that require a path as input, we could either leave it as is and remember to use a tab there, too, or we pre-process the input. 
```abap
* { "contains/slash": { "test": 1 } } or better { "contains\/slash": { "test": 1 } }
r->get( '/contains/slash/test' ). " never worked
r->get( |/contains\tslash/test| ). " works with this PR
r->get( …
```
> Special characters (also nodes containing `/`)

- src/core/zcl_ajson.clas.locals_imp.abap
The PR adds a minimal sanity check. This prevents, for example, XML or plain text data from being parsed.
The check is a few milliseconds, which is fine in general. It does have a significant impact on the benchmark, which parses about a million JSON strings.
I included a small performance improvement in the parser, which speeds things up, esp. for larger JSON data.
> Add sanity check

- docsite/docs/30-basics.md
Very nice doc site! You should add the link to the repo meta here:
Ref #203
PS: `ajson.org` or `ajson.dev` ares available.
> docs: slash in attributes
